### ISSUE TITLE
Panic from query

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#24]
```
2017/12/23 19:59:56 http: panic serving [::1]:53740: reflect: call of reflect.Value.Interface on zero Value
goroutine 27 [running]:
net/http.(*conn).serve.func1(0xc4268fc000)
	/usr/local/go/src/net/http/server.go:1721 +0xd0
panic(0x18febc0, 0xc4262e0f00)
	/usr/local/go/src/runtime/panic.go:489 +0x2cf
reflect.valueInterface(0x0, 0x0, 0x0, 0x1, 0x19cebc0, 0x0)
	/usr/local/go/src/reflect/value.go:930 +0x1fa
reflect.Value.Interface(0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/reflect/value.go:925 +0x44
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).marshalNonProtoField(0xc4201567b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x9, 0x193)
	/Users/buchanae/src/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go:80 +0x5c4
github.com/grpc-ecosystem/grpc-gateway/runtime.(*JSONPb).Marshal(0xc4201567b0, 0x0, 0x0, 0x6, 0x2088100, 0xc4262ccf30, 0x1a1743f, 0x5)
	/Users/buchanae/src/github.com/grpc-ecosystem/grpc-gateway/runtime/marshal_jsonpb.go:29 +0x174
github.com/bmeg/arachne/graphserver.(*MarshalClean).Marshal(0xc420192230, 0x1908ce0, 0xc4262ccf90, 0xc4262ccf30, 0xc4262ccf90, 0xc4262ccf30, 0x0, 0x0)
	/Users/buchanae/src/github.com/bmeg/arachne/graphserver/webserver.go:39 +0x99
github.com/grpc-ecosystem/grpc-gateway/runtime.handleForwardResponseStreamError(0x1ed5301, 0x1edae80, 0xc420192230, 0x1ed8380, 0xc42018e1c0, 0x1ecbf00, 0xc4262ccf30)
	/Users/buchanae/src/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go:151 +0xae
github.com/grpc-ecosystem/grpc-gateway/runtime.ForwardResponseStream(0x3162000, 0xc4201fc2d0, 0xc425592050, 0x1edae80, 0xc420192230, 0x1ed8380, 0xc42018e1c0, 0xc4255ae400, 0xc4201308a0, 0x2086e10, ...)
	/Users/buchanae/src/github.com/grpc-ecosystem/grpc-gateway/runtime/handler.go:55 +0x91d
github.com/bmeg/arachne/aql.RegisterQueryHandler.func1(0x1ed8380, 0xc42018e1c0, 0xc4255ae400, 0xc420019f20)
	/Users/buchanae/src/github.com/bmeg/arachne/aql/aql.pb.gw.go:561 +0x3a1
github.com/grpc-ecosystem/grpc-gateway/runtime.(*ServeMux).ServeHTTP(0xc425592050, 0x1ed8380, 0xc42018e1c0, 0xc4255ae400)
	/Users/buchanae/src/github.com/grpc-ecosystem/grpc-gateway/runtime/mux.go:198 +0x10f5
github.com/gorilla/mux.(*Router).ServeHTTP(0xc4201906c0, 0x1ed8380, 0xc42018e1c0, 0xc4255ae400)
	/Users/buchanae/src/github.com/gorilla/mux/mux.go:150 +0x101
net/http.serverHandler.ServeHTTP(0xc420089600, 0x1ed8380, 0xc42018e1c0, 0xc4255ae200)
	/usr/local/go/src/net/http/server.go:2568 +0x92
net/http.(*conn).serve(0xc4268fc000, 0x1ed91c0, 0xc4201b9480)
	/usr/local/go/src/net/http/server.go:1825 +0x612
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2668 +0x2ce
```

**Comment by buchanae** [comment]
The query:
```
import aql

conn = aql.Connection("http://localhost:8000")
G = conn.graph("het")

print G.query().V().first()
```

**Comment by kellrott** [comment]
What was loaded in the graph?

**Comment by buchanae** [comment]
This is what loaded the graph. Most of this code is loading log files. https://gist.github.com/buchanae/f2a18d023b691dbec958098518a79baa

I suspect it's either that it's only vertices, or it has something to do with serialization of the properties.

**Comment by buchanae** [comment]
I'll try to make a reduced test case. Probably just make a few Tasks and write them into the graph without edges.

**Comment by kellrott** [comment]
Does arachne dump work?

**Comment by kellrott** [comment]
There is a known issue with `G.query().first()` (forgetting the `.V()` or `.E()`), but this is a different one.

**Comment by kellrott** [comment]
I'm getting error on the client:
```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    print G.query().V().first()
  File "/Users/ellrott/workspaces/arachne_alt/src/github.com/bmeg/arachne/aql.py", line 304, in first
    return list(self.execute())[0]
IndexError: list index out of range
```

But thats because client library doesn't check it got a zero length response before getting the first element (no data in the database).

This works (again, for no data in the graph):
```
print list(G.query().V().limit(1))
```

**Comment by kellrott** [comment]
I added test data file to the project.

```
./bin/arachne create test
./bin/arachne load --graph test --vertex src/github.com/bmeg/arachne/test/graph.1.verts --edge src/github.com/bmeg/arachne/test/graph.1.edges
```

With that, the query code:
```
import aql
conn = aql.Connection("http://localhost:8000")
G = conn.graph("test")
print list(G.query().V())
```

I noted that a null id vertex was inserted into the graph as well. That is a bug

**Comment by kellrott** [comment]
Unless there is any other additional info, consider this closed
