### ISSUE TITLE
db/bolt: panic

### ISSUE THREAD

**Issue by buchanae** [bmeg/arachne#76]
```
arachne server --bolt arachne.db
2018/02/27 19:39:25 Starting Server
2018/02/27 19:39:25 Starting BOLTDB
2018/02/27 19:39:25 TCP+RPC server listening on 8202
2018/02/27 19:39:25 HTTP proxy connecting to localhost:8202
2018/02/27 19:39:25 Fields: graphql.Fields{}
2018/02/27 19:39:25 GraphQL Schema: {Query <nil> <nil> [] []}
2018/02/27 19:39:25 HTTP API listening on port: 8201
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa7dbc1]

goroutine 109 [running]:
github.com/bmeg/arachne/timestamp.(*Timestamp).Touch(0x0, 0xc420464230, 0x6)
	/home/ubuntu/src/github.com/bmeg/arachne/timestamp/timestamp.go:20 +0x111
github.com/bmeg/arachne/kvgraph.(*KVGraph).AddGraph(0xc420288940, 0xc420464230, 0x6, 0xc4204664d0, 0xc42046a540)
	/home/ubuntu/src/github.com/bmeg/arachne/kvgraph/kvgraph.go:24 +0x4a
github.com/bmeg/arachne/graphserver.(*GraphEngine).AddGraph(0xc4202539c0, 0xc420464230, 0x6, 0xf5c900, 0xc420466401)
	/home/ubuntu/src/github.com/bmeg/arachne/graphserver/graph_engine.go:31 +0x47
github.com/bmeg/arachne/graphserver.(*ArachneServer).AddGraph(0xc4202539c0, 0xf565e0, 0xc4202df230, 0xc42046a560, 0xc4202539c0, 0x0, 0xc420449a70)
	/home/ubuntu/src/github.com/bmeg/arachne/graphserver/server.go:136 +0x47
github.com/bmeg/arachne/aql._Edit_AddGraph_Handler(0xe0d240, 0xc4202539c0, 0xf565e0, 0xc4202df230, 0xc4204664d0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/home/ubuntu/src/github.com/bmeg/arachne/aql/aql.pb.go:2086 +0x241
google.golang.org/grpc.(*Server).processUnaryRPC(0xc4200db080, 0xf5b5e0, 0xc420484600, 0xc420283a40, 0xc420275710, 0x1504248, 0x0, 0x0, 0x0)
	/home/ubuntu/src/google.golang.org/grpc/server.go:920 +0x848
google.golang.org/grpc.(*Server).handleStream(0xc4200db080, 0xf5b5e0, 0xc420484600, 0xc420283a40, 0x0)
	/home/ubuntu/src/google.golang.org/grpc/server.go:1142 +0x1318
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc4202ac600, 0xc4200db080, 0xf5b5e0, 0xc420484600, 0xc420283a40)
	/home/ubuntu/src/google.golang.org/grpc/server.go:637 +0x9f
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/home/ubuntu/src/google.golang.org/grpc/server.go:635 +0xa1
```

**Comment by kellrott** [comment]
I think this was fixed in the most recent set of PR merges. Can you try again?

**Comment by kellrott** [comment]
Is this still an issue?

**Comment by buchanae** [comment]
I don't remember the exact steps to reproduce; maybe it was just from starting the server. Anyway, looks ok now.
